Minor code and wording changes

diff --git a/mqtt_ups_sched b/mqtt_ups_sched
--- a/mqtt_ups_sched
+++ b/mqtt_ups_sched
@@ -32,7 +32,7 @@
 
 # mqtt_ups_sched
 # Simple UPS command scheduler script (mqtt_ups_sched) for FreeBSD.
-# Triggers a timed command from the specificified MQTT state event.
+# Triggers a timed command if the Inverter/UPS report battery mode operation.
 # Requires a running MQTT broker to query data from device in real-time.
 # Debug script.
 #set -x
@@ -40,7 +40,7 @@
 # Set environment.
 PATH=${PATH}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
 SCRIPTNAME="mqtt_ups_sched"
-VERSION="1.9.05"
+VERSION="1.9.06"
 
 cmd_version() {
 	echo "${SCRIPTNAME} ${VERSION}"
@@ -71,6 +71,7 @@ TIMEOUT_CMD="timeout"
 TIMEOUT_COUNT="5"
 SUB_CMD="mosquitto_sub"
 BC_CMD="bc"
+SYSRC_CMD="sysrc"
 DEFAULT_NAME="UPS"
 DEFAULT_IP="localhost"
 DEFAULT_PORT="1883"
@@ -140,7 +141,7 @@ DEVICE_NAME="${DEFAULT_NAME}"
 # Set the minimum battery voltage to be considered as "system battery low" mode, please use an integer or float value here.
 DEVICE_BATT_LOW=""
 
-# Set the battery inatallation date in "YYYYMMDD" for logging and reference.
+# Set the battery installation date in "YYYYMMDD" for logging and reference.
 DEVICE_BATT_INSTALL=""
 
 # Set the battery max age "count" in years before replacement for logging and reference, please use an integer value here.
@@ -170,22 +171,22 @@ EOF
 
 	# Initialize run-time variables.
 	if [ -f "${CONFIG_FILE}" ]; then
-		BROKER_IP=$(sysrc -f ${CONFIG_FILE} -qn BROKER_IP)
-		BROKER_PORT=$(sysrc -f ${CONFIG_FILE} -qn BROKER_PORT)
-		BROKER_TOPIC_BATTVOLT=$(sysrc -f ${CONFIG_FILE} -qn BROKER_TOPIC_BATTVOLT)
-		BROKER_TOPIC_DEVSTATE=$(sysrc -f ${CONFIG_FILE} -qn BROKER_TOPIC_DEVSTATE)
-		BROKER_TOPIC_GRIDMODE=$(sysrc -f ${CONFIG_FILE} -qn BROKER_TOPIC_GRIDMODE)
-		BROKER_TOPIC_BATTMODE=$(sysrc -f ${CONFIG_FILE} -qn BROKER_TOPIC_BATTMODE)
-		BROKER_TOPIC_STATS=$(sysrc -f ${CONFIG_FILE} -qn BROKER_TOPIC_STATS)
-		DEVICE_NAME="$(sysrc -f ${CONFIG_FILE} -qn DEVICE_NAME)"
-		DEVICE_BATT_LOW=$(sysrc -f ${CONFIG_FILE} -qn DEVICE_BATT_LOW)
-		DEVICE_BATT_INSTALL=$(sysrc -f ${CONFIG_FILE} -qn DEVICE_BATT_INSTALL)
-		DEVICE_BATT_MAXAGE=$(sysrc -f ${CONFIG_FILE} -qn DEVICE_BATT_MAXAGE)
-		SYS_SHUTDOWN_CMD=$(sysrc -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_CMD)
-		SYS_SHUTDOWN_DELAY=$(sysrc -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_DELAY)
-		SYS_LOWBATT_FASTSHUTDOWN=$(sysrc -f ${CONFIG_FILE} -qn SYS_LOWBATT_FASTSHUTDOWN)
-		SYS_BEEP_ENABLE=$(sysrc -f ${CONFIG_FILE} -qn SYS_BEEP_ENABLE)
-		SYS_RETRY_COUNT=$(sysrc -f ${CONFIG_FILE} -qn SYS_RETRY_COUNT)
+		BROKER_IP=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_IP)
+		BROKER_PORT=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_PORT)
+		BROKER_TOPIC_BATTVOLT=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_TOPIC_BATTVOLT)
+		BROKER_TOPIC_DEVSTATE=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_TOPIC_DEVSTATE)
+		BROKER_TOPIC_GRIDMODE=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_TOPIC_GRIDMODE)
+		BROKER_TOPIC_BATTMODE=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_TOPIC_BATTMODE)
+		BROKER_TOPIC_STATS=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_TOPIC_STATS)
+		DEVICE_NAME="$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn DEVICE_NAME)"
+		DEVICE_BATT_LOW=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn DEVICE_BATT_LOW)
+		DEVICE_BATT_INSTALL=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn DEVICE_BATT_INSTALL)
+		DEVICE_BATT_MAXAGE=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn DEVICE_BATT_MAXAGE)
+		SYS_SHUTDOWN_CMD=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_CMD)
+		SYS_SHUTDOWN_DELAY=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_DELAY)
+		SYS_LOWBATT_FASTSHUTDOWN=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_LOWBATT_FASTSHUTDOWN)
+		SYS_BEEP_ENABLE=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_BEEP_ENABLE)
+		SYS_RETRY_COUNT=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_RETRY_COUNT)
 	else
 		echo "Error: Config file not found, exiting."
 		exit 1
@@ -205,46 +206,52 @@ check_config() {
 		exit 1
 	fi
 
+	# Ensure 'bc' command is present.
+	if ! which "${SYSRC_CMD}" >/dev/null; then
+		echo "Required '${SYSRC_CMD}' command not found, exiting!"
+		exit 1
+	fi
+
 	if [ -z "${DEVICE_NAME}" ]; then
 		echo "=> Setting default device name."
-		sysrc -f ${CONFIG_FILE} DEVICE_NAME="${DEFAULT_NAME}"
-		DEVICE_NAME=$(sysrc -f ${CONFIG_FILE} -qn DEVICE_NAME)
+		${SYSRC_CMD} -f ${CONFIG_FILE} DEVICE_NAME="${DEFAULT_NAME}"
+		DEVICE_NAME=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn DEVICE_NAME)
 	fi
 
 	if [ -z "${BROKER_IP}" ]; then
 		echo "=> Setting default broker ip:"
-		sysrc -f ${CONFIG_FILE} BROKER_IP="${DEFAULT_PORT}"
-		BROKER_IP=$(sysrc -f ${CONFIG_FILE} -qn BROKER_IP)
+		${SYSRC_CMD} -f ${CONFIG_FILE} BROKER_IP="${DEFAULT_PORT}"
+		BROKER_IP=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_IP)
 	fi
 
 	if [ -z "${BROKER_PORT}" ]; then
 		echo "=> Setting default broker port:"
-		sysrc -f ${CONFIG_FILE} BROKER_PORT="${DEFAULT_PORT}"
-		BROKER_PORT=$(sysrc -f ${CONFIG_FILE} -qn BROKER_PORT)
+		${SYSRC_CMD} -f ${CONFIG_FILE} BROKER_PORT="${DEFAULT_PORT}"
+		BROKER_PORT=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn BROKER_PORT)
 	fi
 
 	if [ -z "${SYS_SHUTDOWN_CMD}" ]; then
 		echo "=> Setting default shutdown command:"
-		sysrc -f ${CONFIG_FILE} SYS_SHUTDOWN_CMD="${DEFAULT_CMD}"
-		SYS_SHUTDOWN_CMD=$(sysrc -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_CMD)
+		${SYSRC_CMD} -f ${CONFIG_FILE} SYS_SHUTDOWN_CMD="${DEFAULT_CMD}"
+		SYS_SHUTDOWN_CMD=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_CMD)
 	fi
 
 	if [ -z "${SYS_SHUTDOWN_DELAY}" ]; then
 		echo "=> Setting default shutdown delay:"
-		sysrc -f ${CONFIG_FILE} SYS_SHUTDOWN_DELAY="${DEFAULT_DELAY}"
-		SYS_SHUTDOWN_DELAY=$(sysrc -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_DELAY)
+		${SYSRC_CMD} -f ${CONFIG_FILE} SYS_SHUTDOWN_DELAY="${DEFAULT_DELAY}"
+		SYS_SHUTDOWN_DELAY=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_SHUTDOWN_DELAY)
 	fi
 
 	if [ -z "${SYS_BEEP_ENABLE}" ]; then
 		echo "=> Setting default system beep:"
-		sysrc -f ${CONFIG_FILE} SYS_BEEP_ENABLE="${DEFAULT_BEEP}"
-		SYS_BEEP_ENABLE=$(sysrc -f ${CONFIG_FILE} -qn SYS_BEEP_ENABLE)
+		${SYSRC_CMD} -f ${CONFIG_FILE} SYS_BEEP_ENABLE="${DEFAULT_BEEP}"
+		SYS_BEEP_ENABLE=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_BEEP_ENABLE)
 	fi
 
 	if [ -z "${SYS_RETRY_COUNT}" ]; then
 		echo "=> Setting default retry count:"
-		sysrc -f ${CONFIG_FILE} SYS_RETRY_COUNT="${DEFAULT_RETRY}"
-		SYS_RETRY_COUNT=$(sysrc -f ${CONFIG_FILE} -qn SYS_RETRY_COUNT)
+		${SYSRC_CMD} -f ${CONFIG_FILE} SYS_RETRY_COUNT="${DEFAULT_RETRY}"
+		SYS_RETRY_COUNT=$(${SYSRC_CMD} -f ${CONFIG_FILE} -qn SYS_RETRY_COUNT)
 	fi
 
 	# If below parameters are not configured then inform and exit.
